name: New PR

on:
  pull_request:
    types: [opened, reopened, unlabeled, labeled]
  schedule:
    - cron: '10,22,34,46,58 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  check-add-new-pr-label:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/add_New_PR_label.yml
    secrets: inherit

  remove-new-pr-label-job:
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/remove_New_PR_label.yml
    secrets: inherit

  check-remove-newpr-labels:
    needs: remove-new-pr-label-job
    uses: ./.github/workflows/do-not-merge-new-pr.yml
    secrets: inherit

  block-merge-new-pr:
    needs: check-add-new-pr-label
    uses: ./.github/workflows/do-not-merge-new-pr.yml
    secrets: inherit
