name: New PR

on:
  pull_request:
    types: [opened, reopened, unlabeled, labeled]
  schedule:
    - cron: '10,22,34,46,58 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  check-add-new-pr-label:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/add_New_PR_label.yml
    secrets: inherit

  remove-new-pr-label-job:
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/remove_New_PR_label.yml
    secrets: inherit

  check-remove-newpr-labels:
    if: github.event_name == 'schedule'
    needs: remove-new-pr-label-job
    runs-on: ubuntu-latest
    steps:
      - name: Get open PR numbers
        id: get_prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            return prs.data.map(pr => pr.number);

      - name: Run Do Not Merge on each PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumbers = ${{ steps.get_prs.outputs.result }};
            for (const pr_number of prNumbers) {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'do-not-merge-new-pr.yml',
                ref: context.ref.replace('refs/heads/', ''),
                inputs: {
                  pr_number
                }
              });
            }
