# This is a basic workflow to help you get started with Actions

name: Remove New PR Label

# Controls when the workflow will run
on:
  # Triggers the workflow

  schedule:
    # - cron: '0 * * * *' # Runs every hour
    - cron: '10,21,47 * * * *' # Runs every 30 mins

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  remove-old-newpr-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove "New PR" label if PR is older than 24 hours
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = 'New PR';

            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            const now = new Date();

            for (const pr of prs.data) {
              const createdAt = new Date(pr.created_at);
              const hoursSinceCreation = (now - createdAt) / (1000 * 60 * 60);

              if (hoursSinceCreation > 1) {
                const labels = pr.labels.map(l => l.name);
                if (labels.includes(labelToRemove)) {
                  console.log(`Removing "${labelToRemove}" from PR #${pr.number} (created ${hoursSinceCreation.toFixed(2)} hours ago)`);

                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: labelToRemove
                  });
                }
              }
            }
