# This is a basic workflow to help you get started with Actions

name: Add New PR Label

# Controls when the workflow will run
on:
  # Triggers the workflow
  pull_request:
    types: [opened, reopened, unlabeled]

  schedule:
    # - cron: '0 * * * *' # Runs every hour
    - cron: '*/15 * * * *' # Runs every 15 mins

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  manage-label:
    runs-on: ubuntu-latest
    steps:
      # Add "New PR" label when PR is opened or reopened
      - name: Add "New PR" label
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
        uses: PauMAVA/add-remove-label-action@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: New PR

      # Remove "New PR" label after 24 hours (scheduled job)
      - name: Remove "New PR" label if PR is older than 24 hours
        if: github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = "New PR";
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              per_page: 100
            });
            const now = new Date();
            for (const pr of prs) {
              const created = new Date(pr.created_at);
              const hasLabel = pr.labels.some(label => label.name === labelName);
              # if (hasLabel && (now - created) > 24 * 60 * 60 * 1000) {
              if (hasLabel && (now - created) > 15 * 60 * 1000) { # 15 mins
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  name: labelName
                });
              }
            }

  readd-label:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'New PR'
    steps:
      - name: Check PR age and re-add label if < 24 hours
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = github.event.pull_request;
            const labelName = 'New PR';
            const created = new Date(pr.created_at);
            const now = new Date();
            // Less than 24 hours old?
            # if ((now - created) < 24 * 60 * 60 * 1000) {
            if ((now - created) < 15 * 60 * 1000) { # 15 mins
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [labelName]
              });
            }
