name: New PR Label

on:
  pull_request:
    types: [opened, reopened, unlabeled, labeled]

  schedule:
    # - cron: '0 * * * *' # Runs every hour
    - cron: '10,22,34,46,58 * * * *' # Runs every 12 mins

  workflow_dispatch: # Run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  check-add-new-pr-label: # Adds label if PR < time
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/add_New_PR_label.yml

  check-remove-newpr-labels:
    uses: ./.github/workflows/remove_New_PR_label.yml
