# This is a basic workflow to help you get started with Actions

name: Remove New PR Label

# Controls when the workflow will run
on:
  # Triggers the workflow

  schedule:
    # - cron: '0 * * * *' # Runs every hour
    - cron: '10,21,47 * * * *' # Runs every 30 mins

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  old-version-of-remove-old-newpr-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Old version of Remove "New PR" label if PR is older than 24 hours
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = 'New PR';

            console.log(`Old version test.`);
