# This is a basic workflow to help you get started with Actions

name: Remove New PR Label

# Controls when the workflow will run
on:
  # Triggers the workflow

  schedule:
    # - cron: '0 * * * *' # Runs every hour
    - cron: '10,21,47 * * * *' # Runs every 30 mins

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  maybe-remove-label:
    runs-on: ubuntu-latest
    steps:

      # Remove "New PR" label after 24 hours (scheduled job)
      - name: Remove "New PR" label if PR is older than 24 hours
        # if: github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelName = "New PR";
            # console.log(`Finding PRs with Label "${labelName}".`);
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              per_page: 100
            });
            # console.log(`Found PRs.`);
            # const now = new Date();
            # for (const pr of prs) {
            #   const created = new Date(pr.created_at);
            #  const hasLabel = pr.labels.some(label => label.name === labelName);
            #  if (hasLabel && (now - created) > 24 * 60 * 60 * 1000) {
            #  if (hasLabel && (now - created) > 15 * 60 * 1000) { # 15 mins
            #    await github.rest.issues.removeLabel({
            #      owner: context.repo.owner,
            #       repo: context.repo.repo,
            #      issue_number: pr.number,
            #      name: labelName
            #    });
            #  }
            #}
