name: New PR Label

on:
  pull_request:
    types: [opened, reopened, unlabeled]

  schedule:
    # - cron: '0 * * * *' # Runs every hour
    - cron: '10,22,34,46,58 * * * *' # Runs every 12 mins

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  check-add-new-pr-label:
    if: github.event_name == 'pull_request'
    call-add-New-PR-label:
      uses: ./.github/workflows/add_New_PR_label.yml

  check-remove-newpr-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove "New PR" label if PR is older than 24 hours
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = 'New PR';

            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            const now = new Date();

            for (const pr of prs.data) {
              const createdAt = new Date(pr.created_at);
              const hoursSinceCreation = (now - createdAt) / (1000 * 60 * 60);

              if (hoursSinceCreation > 1) {
                const labels = pr.labels.map(l => l.name);
                if (labels.includes(labelToRemove)) {
                  console.log(`Removing "${labelToRemove}" from PR #${pr.number} (created ${hoursSinceCreation.toFixed(2)} hours ago)`);

                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: labelToRemove
                  });
                }
              }
            }

  prevent-merge-new-pr:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'New PR') }}
    name: Prevent New PRs Merging 2
    runs-on: ubuntu-latest
    steps:
      - name: PR has New PR label2.
        run: |
          echo "Pull request is labeled as 'New PR' 2"
          exit 1
