# This is a basic workflow to help you get started with Actions

name: Add New PR Label

# Controls when the workflow will run
on:
  # Triggers the workflow
  pull_request:
    types: [opened, reopened, unlabeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: PauMAVA/add-remove-label-action@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add: New PR
