name: Re-add "New PR" Label if Removed Early

on:
  pull_request:
    types: [unlabeled]

jobs:
  readd-label:
  uses: actions/github-script@v7
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const pr = context.payload.pull_request;
      const labelName = 'New PR';
      const created = new Date(pr.created_at);
      const now = new Date();
      // Less than 24 hours old?
      if ((now - created) < 24 * 60 * 60 * 1000) {
        await github.rest.issues.addLabels({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: pr.number,
          labels: [labelName]
        });
      }

