name: Re-add New PR Label if removed within 24h

on:
  pull_request:
    types:
      - unlabeled

jobs:
  check-label-removal:
    if: github.event.label.name == 'New PR'
    runs-on: ubuntu-latest
    steps:
      - name: Check PR creation time
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const labelName = context.payload.label.name;

            const createdAt = new Date(pr.created_at);
            const now = new Date();

            const hoursSinceCreation = (now - createdAt) / (1000 * 60 * 60);

            if (hoursSinceCreation <= 24) {
              console.log(`Label "${labelName}" was removed within 24 hours of PR creation. Re-adding it.`);
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [labelName]
              });
            } else {
              console.log(`More than 24 hours since PR creation. No action taken.`);
            }
