name: Remove New PR Label

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove "New PR" label if PR is older than 24 hours
        uses: actions/github-script@v7
        with:
          script: |
            const labelToRemove = 'New PR';

            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            const now = new Date();

            for (const pr of prs.data) {
              const createdAt = new Date(pr.created_at);
              const hoursSinceCreation = (now - createdAt) / (1000 * 60 * 60);

              if (hoursSinceCreation > 0.5) {
                const labels = pr.labels.map(l => l.name);
                if (labels.includes(labelToRemove)) {
                  console.log(`Removing "${labelToRemove}" from PR #${pr.number} (created ${hoursSinceCreation.toFixed(2)} hours ago)`);

                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: labelToRemove
                  });
                  
                  await github.rest.actions.createWorkflowDispatch({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    workflow_id: 'do-not-merge-new-pr.yml',
                    ref: context.ref.replace('refs/heads/', ''),
                    inputs: {
                      pr.number
                    }
                  });
                  
                  
                }
              }
            }
